"""Frozen legacy Stripchat-family runner shared with XHamsterLive.

This module is the mechanical extraction of the pre-hardening
``stripchat_core`` implementation. It exists so ``XHamsterLiveRunner`` can
keep its current behavior while ``stripchat_core.StripchatRunner`` is
rewritten against the hardened contracts.

FROZEN: do not edit this file for Stripchat hardening work. Only a proven
mechanical-extraction bug exposed by an XHamsterLive golden test justifies a
change here.
"""

import json
import os
import time
import urllib.error
import urllib.request

from selenium.webdriver.common.by import By

import ctb_core as ctb
from ctb_core import CTBRunner


class LegacyStripchatFamilyPaths:
    def __init__(self, session_folder):
        self.session_folder = session_folder
        self.vpn_list = os.path.join(session_folder, "sc_vpn_list.txt")
        self.local_list = os.path.join(session_folder, "sc_local_list.txt")
        self.candidates = os.path.join(session_folder, "sc_candidates.txt")
        self.verified = os.path.join(session_folder, "FINAL_BLOCKED.txt")
        self.debug = os.path.join(session_folder, "sc_debug_log.txt")
        self.metadata = os.path.join(session_folder, "sc_metadata.json")


class LegacyStripchatFamilyRunner(CTBRunner):
    # Inherited session/master helpers are shared; profile metadata is CTB-only.
    supports_location_profiles = False
    platform_name = "Stripchat"
    site_domain = "stripchat.com"
    api_host = "go.stripchat.com"
    profile_dir_name = "uc_profile_sc"

    def _build_paths(self, session_path):
        return LegacyStripchatFamilyPaths(session_path)

    def _model_url(self, username):
        return f"https://{self.site_domain}/{username}/"

    def _api_models_url(self, limit, offset):
        return f"https://{self.api_host}/api/models?limit={limit}&offset={offset}"

    def _has_hidden_text(self, page_src_lower):
        src = page_src_lower or ""
        return (
            "account hidden" in src
            or "account has been hidden" in src
            or "account is hidden" in src
        )

    def _has_disabled_text(self, page_src_lower):
        src = page_src_lower or ""
        return (
            "account disabled" in src
            or "account has been disabled" in src
            or "account is disabled" in src
            or "account deleted" in src
            or "model deleted" in src
        )

    def set_session(self, session_path):
        self.session_folder = session_path
        self.paths = self._build_paths(session_path)

    def add_manual_to_master(self, username):
        if not username:
            return
        username = username.strip().lower()
        url = self._model_url(username)
        norm = self._normalize_url(url)
        manual_path = self.get_manual_list_path()

        try:
            existing = set()
            if os.path.exists(manual_path):
                with open(manual_path, "r") as f:
                    existing = set(
                        self._normalize_url(line) for line in f if line.strip()
                    )

            if norm not in existing:
                with open(manual_path, "a") as f:
                    f.write(norm + "\n")
                self.log(
                    f"[INFO] Manually added {norm} to {self.platform_name} manual list."
                )

            self.compile_master_list()
        except Exception as exc:
            self.log(f"[ERROR] Failed to add manual model: {exc}")

    def _fetch_json(self, url):
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "Mozilla/5.0",
                "Accept": "application/json",
            },
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            payload = resp.read().decode("utf-8", errors="replace")
        return json.loads(payload)

    def fetch_models_all(
        self,
        mode_name,
        robust=False,
        limit=500,
        passes=None,
        min_seen=1,
        save_metadata=False,
    ):
        self._ensure_session()
        if self._should_stop():
            self.log("[INFO] Stop requested before API fetch started.")
            return set()
        self.log(f"[INFO] Contacting {self.platform_name} API for {mode_name} list...")
        if passes is None:
            passes = 2 if robust else 1
        if passes < 1:
            passes = 1
        if passes > 1:
            self.log(f"[INFO] Robust mode enabled ({passes} passes).")

        min_seen = max(1, min_seen)
        if min_seen > passes:
            min_seen = passes

        seen_counts = {}
        metadata_counts = {}

        for pass_num in range(passes):
            if self._should_stop():
                self.log("[INFO] Stop requested. Ending API fetch.")
                break
            if passes > 1:
                self.log(f"[INFO] Pass {pass_num + 1}/{passes}...")

            offset = 0
            seen_offsets = set()
            pass_seen = set()
            pass_usernames = set()

            while True:
                if self._should_stop():
                    self.log("[INFO] Stop requested. Ending API fetch.")
                    break
                if offset in seen_offsets:
                    self.log("[WARN] Pagination loop detected; stopping.")
                    break
                seen_offsets.add(offset)

                url = self._api_models_url(limit, offset)
                try:
                    data = self._fetch_json(url)
                except Exception as exc:
                    self.log(f"[ERROR] API fetch failed: {exc}")
                    break

                models = data.get("models", [])
                if not isinstance(models, list):
                    self.log("[WARN] Unexpected API response format.")
                    break

                count = data.get("count")
                if count is None:
                    count = len(models)

                if not models or count <= 0:
                    break

                for model in models:
                    username = model.get("username")
                    if username:
                        username_key = username.strip().lower()
                        link = self._model_url(username)
                        pass_seen.add(self._normalize_url(link))
                        if username_key:
                            pass_usernames.add(username_key)

                total = data.get("total")
                offset += count
                if isinstance(total, int) and total > 0 and offset >= total:
                    break
                if count < limit and (not isinstance(total, int) or total <= 0):
                    break

                time.sleep(0.2)

            if self._should_stop():
                break

            for link in pass_seen:
                seen_counts[link] = seen_counts.get(link, 0) + 1
            for name in pass_usernames:
                metadata_counts[name] = metadata_counts.get(name, 0) + 1

            if pass_num < passes - 1:
                time.sleep(0.4)

        online_set = {
            link for link, count in seen_counts.items() if count >= min_seen
        }
        if min_seen > 1:
            self.log(
                f"[INFO] {mode_name} stability filter: {min_seen}/{passes} passes."
            )

        self.log(
            f"[INFO] {mode_name} fetch complete. Unique models: {len(online_set)}"
        )
        if save_metadata and metadata_counts:
            try:
                with open(self.paths.metadata, "w") as handle:
                    json.dump(
                        {"passes": passes, "counts": metadata_counts}, handle
                    )
                self.log(
                    f"[INFO] Metadata snapshot saved ({len(metadata_counts)} records)."
                )
            except Exception as exc:
                self.log(f"[WARN] Failed to save metadata snapshot: {exc}")
        return online_set

    def step_vpn_list(self, headless=True):
        self.log("[INFO] Step 1: VPN list (VPN ON).")
        models = self.fetch_models_all("VPN List", robust=True, save_metadata=True)
        if models:
            self._write_list(self.paths.vpn_list, models)
            self.log(f"[INFO] VPN list saved: {self.paths.vpn_list}")
        else:
            self.log("[WARN] VPN list empty. Nothing saved.")

    def step_local_list(self, headless=True):
        self.log("[INFO] Step 2: Local list (VPN OFF).")
        models = self.fetch_models_all("Local List", robust=True)
        if models:
            self._write_list(self.paths.local_list, models)
            self.log(f"[INFO] Local list saved: {self.paths.local_list}")
        else:
            self.log("[WARN] Local list empty. Nothing saved.")

    def compare_lists(self):
        self._ensure_session()
        if not os.path.exists(self.paths.vpn_list) or not os.path.exists(
            self.paths.local_list
        ):
            self.log("[WARN] Missing files. Run steps 1 and 2 first.")
            return

        self.log("[INFO] Loading lists...")
        with open(self.paths.vpn_list, "r") as handle:
            vpn = set(self._normalize_url(line) for line in handle if line.strip())
        with open(self.paths.local_list, "r") as handle:
            local = set(self._normalize_url(line) for line in handle if line.strip())

        raw_suspects = vpn - local

        self.log("[INFO] Preliminary analysis:")
        self.log(f"[INFO] VPN list: {len(vpn)}")
        self.log(f"[INFO] Local list: {len(local)}")
        self.log(f"[INFO] Missing locally: {len(raw_suspects)}")

        metadata_counts = {}
        metadata_passes = None
        if os.path.exists(self.paths.metadata):
            self.log("[INFO] Loading VPN snapshot for stability check...")
            try:
                with open(self.paths.metadata, "r") as handle:
                    metadata = json.load(handle)
                if isinstance(metadata, dict) and "counts" in metadata:
                    metadata_counts = metadata.get("counts", {})
                    metadata_passes = metadata.get("passes")
                elif isinstance(metadata, dict):
                    metadata_counts = metadata
            except Exception as exc:
                self.log(f"[WARN] Failed to load metadata snapshot: {exc}")
        else:
            self.log("[WARN] Metadata snapshot not found. Stability filter skipped.")

        stability_min = 0
        if metadata_counts:
            numeric_counts = [
                v for v in metadata_counts.values() if isinstance(v, int)
            ]
            if numeric_counts:
                max_seen = max(numeric_counts)
                if max_seen >= 2:
                    stability_min = 2
                    stability_passes = metadata_passes or max_seen

        final_candidates = []
        if stability_min:
            self.log(
                "[INFO] Filtering unstable VPN entries (seen < "
                f"{stability_min}/{stability_passes} passes)."
            )
        for link in raw_suspects:
            username = link.rstrip("/").split("/")[-1]
            username_key = username.lower()
            seen = metadata_counts.get(username_key) if metadata_counts else None
            if stability_min and seen is not None and seen < stability_min:
                continue
            final_candidates.append(link)

        recheck_passes = 2
        if final_candidates and recheck_passes > 0:
            self.log(
                "[INFO] VPN should be OFF for local recheck (false positives)."
            )
            self.log(
                f"[INFO] Local recheck enabled ({recheck_passes} passes)."
            )
            local_refresh = self.fetch_models_all(
                "Local Recheck",
                passes=recheck_passes,
                min_seen=1,
            )
            before = len(final_candidates)
            final_candidates = [
                link for link in final_candidates if link not in local_refresh
            ]
            removed = before - len(final_candidates)
            self.log(
                f"[INFO] Local recheck removed {removed} models seen locally."
            )

        final_candidates = sorted(final_candidates)

        with open(self.paths.candidates, "w") as handle:
            for link in final_candidates:
                handle.write(link + "\n")

        with open(self.paths.debug, "w") as handle:
            handle.write("\n".join(final_candidates))

        self.log(f"[INFO] Candidates saved: {self.paths.candidates}")
        self.log(f"[INFO] Debug log saved: {self.paths.debug}")

    def _is_blocked_page(self, driver, page_src_lower):
        if self._has_hidden_text(page_src_lower):
            return True
        try:
            if driver.find_elements(
                By.CSS_SELECTOR,
                ".account-hidden-header, .account-hidden-page",
            ):
                return True
        except Exception:
            pass
        return False

    def _is_disabled_page(self, driver, page_src_lower):
        if self._has_disabled_text(page_src_lower):
            return True
        try:
            if driver.find_elements(
                By.CSS_SELECTOR,
                ".account-disabled-header, .account-disabled-page, .model-deleted-page",
            ):
                return True
        except Exception:
            pass
        return False

    def verify_candidates(self, start_minimized=True, reveal_on_captcha=True):
        self._ensure_session()
        if self._should_stop():
            self.log("[INFO] Stop requested before verification started.")
            return
        if not os.path.exists(self.paths.candidates):
            self.log("[WARN] No candidate file found. Run step 3 first.")
            return

        with open(self.paths.candidates, "r") as handle:
            urls = [line.strip() for line in handle if line.strip()]

        if not urls:
            self.log("[WARN] Candidate list is empty.")
            return

        self.log(f"[INFO] Verification phase ({len(urls)} candidates).")
        self.log("[INFO] VPN should be OFF for verification.")
        self.log("[INFO] Browser will appear if captcha is detected.")
        if start_minimized:
            self.log(
                "[INFO] Browser will hide after captcha and continue in background."
            )
        else:
            self.log("[INFO] Browser will stay visible during verification.")

        prefs = {
            "profile.managed_default_content_settings.images": 1,
            "profile.default_content_setting_values.popups": 1,
            "profile.managed_default_content_settings.popups": 1,
            "profile.content_settings.exceptions.popups.*.setting": 1,
        }

        profile_dir = os.path.join(self.session_folder, self.profile_dir_name)
        os.makedirs(profile_dir, exist_ok=True)

        options = ctb.uc.ChromeOptions()
        options.add_argument("--mute-audio")
        options.add_argument("--disable-popup-blocking")
        options.add_argument("--window-size=1200,900")
        options.add_argument("--no-first-run")
        options.add_argument("--no-default-browser-check")
        options.add_argument("--disable-extensions")
        if start_minimized:
            options.add_argument("--start-minimized")
            options.add_argument("--window-position=-32000,-32000")
            options.add_argument("--window-size=1,1")
        options.add_experimental_option("prefs", prefs)
        options.page_load_strategy = "normal"

        confirmed_blocks = []
        all_batches = []

        all_batches.append([urls[0]])
        batch_size = 5
        remaining_urls = urls[1:]
        if remaining_urls:
            for idx in range(0, len(remaining_urls), batch_size):
                all_batches.append(remaining_urls[idx : idx + batch_size])

        driver = None
        chrome_pids = set()
        chromedriver_pid = None
        chrome_pids_before = (
            ctb._win_get_chrome_pids() if ctb.IS_WINDOWS and ctb._win_get_chrome_pids else set()
        )
        warned_hide_fail = False
        hidden_logged = False
        hider = None

        def is_captcha(title, page_src):
            title_text = (title or "").lower()
            if "just a moment" in title_text:
                return True
            if "verify" in title_text or "cloudflare" in title_text:
                return True

            if page_src:
                src = page_src.lower()
                if "cf-challenge" in src:
                    return True
                if "checking your browser" in src:
                    return True
                if "just a moment" in src:
                    return True
            return False

        def wait_for_captcha_clear():
            while True:
                try:
                    title_now = driver.title
                except Exception:
                    title_now = ""
                try:
                    page_src = driver.page_source
                except Exception:
                    page_src = ""
                if not is_captcha(title_now, page_src):
                    return True
                time.sleep(0.5)

        try:
            driver = ctb._uc_chrome(options=options, user_data_dir=profile_dir)
            self._set_active_driver(driver)
            time.sleep(1.0)

            if ctb.IS_WINDOWS and ctb._win_get_chrome_pids_for_profile:
                try:
                    chromedriver_pid = driver.service.process.pid
                except Exception:
                    chromedriver_pid = None
                chrome_pids = ctb._win_get_chrome_pids_for_profile(profile_dir)
                if not chrome_pids and chromedriver_pid and ctb._win_get_chrome_pids_for_parent:
                    chrome_pids = ctb._win_get_chrome_pids_for_parent(chromedriver_pid)
                if not chrome_pids and ctb._win_get_chrome_pids:
                    chrome_pids = ctb._win_get_chrome_pids() - chrome_pids_before
                if not chrome_pids and ctb._win_get_chrome_pids_for_profile:
                    time.sleep(1.0)
                    chrome_pids = ctb._win_get_chrome_pids_for_profile(profile_dir)
                    if not chrome_pids and chromedriver_pid and ctb._win_get_chrome_pids_for_parent:
                        chrome_pids = ctb._win_get_chrome_pids_for_parent(chromedriver_pid)
                    if not chrome_pids and ctb._win_get_chrome_pids:
                        chrome_pids = ctb._win_get_chrome_pids() - chrome_pids_before
                if start_minimized:
                    if chrome_pids:
                        self.log(
                            "[INFO] Chrome window will be hidden from the taskbar."
                        )
                    else:
                        self.log(
                            "[WARN] Chrome process not found; fallback hide may show in taskbar."
                        )
                if start_minimized and ctb._ChromeWindowHider:
                    hider = ctb._ChromeWindowHider(profile_dir, parent_pid=chromedriver_pid)
                    hider.start()

            def show_window():
                if hider and hider.show():
                    try:
                        driver.set_window_rect(x=120, y=80, width=1200, height=900)
                    except Exception:
                        pass
                    return
                if ctb.IS_WINDOWS:
                    if ctb._win_show_windows_for_profile and ctb._win_show_windows_for_profile(profile_dir) > 0:
                        return
                    if chromedriver_pid and ctb._win_get_chrome_pids_for_parent and ctb._win_show_windows_for_pids:
                        pids = ctb._win_get_chrome_pids_for_parent(chromedriver_pid)
                        if pids:
                            ctb._win_show_windows_for_pids(pids)
                            return
                    pids = ctb._win_get_chrome_pids_for_profile(profile_dir) if ctb._win_get_chrome_pids_for_profile else chrome_pids
                    if pids and ctb._win_show_windows_for_pids:
                        ctb._win_show_windows_for_pids(pids)
                        return
                try:
                    driver.maximize_window()
                except Exception:
                    pass

            def hide_window():
                nonlocal warned_hide_fail
                nonlocal hidden_logged
                if not start_minimized:
                    return False
                if hider and hider.hide():
                    if not hidden_logged:
                        self.log("[INFO] Browser hidden. Continuing in background.")
                        hidden_logged = True
                    return True
                if ctb.IS_WINDOWS:
                    count = 0
                    if ctb._win_hide_windows_for_profile:
                        count = ctb._win_hide_windows_for_profile(profile_dir)
                    if count > 0:
                        if not hidden_logged:
                            self.log("[INFO] Browser hidden. Continuing in background.")
                            hidden_logged = True
                        return True
                    if chromedriver_pid and ctb._win_get_chrome_pids_for_parent and ctb._win_hide_windows_for_pids:
                        count = ctb._win_hide_windows_for_pids(
                            ctb._win_get_chrome_pids_for_parent(chromedriver_pid)
                        )
                        if count > 0:
                            if not hidden_logged:
                                self.log(
                                    "[INFO] Browser hidden. Continuing in background."
                                )
                                hidden_logged = True
                            return True
                    pids = ctb._win_get_chrome_pids_for_profile(profile_dir) if ctb._win_get_chrome_pids_for_profile else chrome_pids
                    if pids and ctb._win_hide_windows_for_pids:
                        count = ctb._win_hide_windows_for_pids(pids)
                        if count > 0:
                            if not hidden_logged:
                                self.log(
                                    "[INFO] Browser hidden. Continuing in background."
                                )
                                hidden_logged = True
                            return True
                    if not warned_hide_fail:
                        self.log(
                            "[WARN] Could not hide Chrome window; it may remain visible."
                        )
                        warned_hide_fail = True
                    return False
                try:
                    driver.set_window_rect(x=-20000, y=0, width=1200, height=900)
                except Exception:
                    pass
                try:
                    driver.minimize_window()
                except Exception:
                    pass
                if not hidden_logged:
                    self.log("[INFO] Browser hidden. Continuing in background.")
                    hidden_logged = True
                return True

            if start_minimized:
                for _ in range(10):
                    if hide_window():
                        break
                    time.sleep(0.2)

            total_batches = len(all_batches)

            for batch_idx, batch in enumerate(all_batches):
                if self._should_stop():
                    self.log("[INFO] Stop requested. Ending verification early.")
                    break
                is_warmup = batch_idx == 0
                batch_num = batch_idx + 1

                if is_warmup:
                    self.log(
                        f"[INFO] Batch {batch_num}/{total_batches} warm-up (1 page)."
                    )
                else:
                    self.log(
                        f"[INFO] Batch {batch_num}/{total_batches} checking {len(batch)} tabs."
                    )

                driver.get(batch[0])
                for url in batch[1:]:
                    driver.execute_script(f"window.open('{url}', '_blank');")

                if start_minimized:
                    for _ in range(5):
                        if hide_window():
                            break
                        time.sleep(0.2)

                start_batch = time.time()
                results = {handle: None for handle in driver.window_handles}
                time.sleep(1.0)

                while True:
                    if self._should_stop():
                        break
                    all_done = True
                    current_handles = driver.window_handles
                    captcha_handled = False

                    timeout_limit = 30.0 if is_warmup else 12.0
                    if time.time() - start_batch > timeout_limit:
                        break

                    for idx, handle in enumerate(current_handles):
                        if handle not in results or results[handle] is not None:
                            continue

                        try:
                            driver.switch_to.window(handle)
                            title_now = driver.title
                            page_src = driver.page_source
                        except Exception:
                            continue

                        if is_captcha(title_now, page_src):
                            self.log(
                                "[WARN] Captcha detected. Please solve in the browser."
                            )
                            if reveal_on_captcha:
                                show_window()
                            wait_for_captcha_clear()
                            self.log("[INFO] Captcha solved. Resuming checks.")
                            if start_minimized:
                                hide_window()
                            start_batch = time.time()
                            try:
                                results = {h: None for h in driver.window_handles}
                            except Exception:
                                results = {}
                            captcha_handled = True
                            break

                        page_src_lower = (page_src or "").lower()
                        if self._is_disabled_page(driver, page_src_lower):
                            self.log(
                                "[INFO] Disabled/deleted account detected; skipping."
                            )
                            results[handle] = "clean"
                            continue
                        is_blocked = self._is_blocked_page(driver, page_src_lower)

                        if is_blocked:
                            if idx < len(batch):
                                confirmed_blocks.append(batch[idx])
                            else:
                                confirmed_blocks.append(driver.current_url)
                            self.log("[INFO] Hidden account detected.")
                            results[handle] = "blocked"
                        else:
                            try:
                                ready = driver.execute_script("return document.readyState")
                            except Exception:
                                ready = ""
                            if ready == "complete":
                                results[handle] = "clean"

                        if results.get(handle) is None:
                            all_done = False

                    if captcha_handled:
                        continue

                    if all_done:
                        break
                    time.sleep(0.5)

                if self._should_stop():
                    break

                for handle in driver.window_handles[1:]:
                    driver.switch_to.window(handle)
                    driver.close()

                if driver.window_handles:
                    driver.switch_to.window(driver.window_handles[0])

                if self._should_stop():
                    break

        except Exception as exc:
            message = str(exc)
            if (
                "invalid session id" in message
                or "session deleted" in message
                or "not connected to DevTools" in message
            ):
                self.log(
                    "[WARN] Browser window was closed. Verification stopped early."
                )
            else:
                self.log(f"[ERROR] Verification failed: {exc}")
        finally:
            if hider:
                hider.stop()
            self._set_active_driver(None)
            ctb.safe_quit(driver)
            try:
                import shutil
                shutil.rmtree(profile_dir, ignore_errors=True)
            except Exception:
                pass

        confirmed_blocks = list(set(self._normalize_url(u) for u in confirmed_blocks if u))
        with open(self.paths.verified, "w") as handle:
            for link in sorted(confirmed_blocks):
                handle.write(link + "\n")
        self.log(f"[INFO] Final list saved: {self.paths.verified}")

        intermediate_files = [
            self.paths.vpn_list,
            self.paths.local_list,
            self.paths.candidates,
            self.paths.metadata,
            self.paths.debug,
        ]
        for file_path in intermediate_files:
            if os.path.exists(file_path):
                try:
                    os.remove(file_path)
                except Exception as exc:
                    self.log(
                        f"[WARN] Failed to delete {os.path.basename(file_path)}: {exc}"
                    )
        self.log("[INFO] Intermediate session files cleaned up.")

        self.compile_master_list()

    def verify_master_list(self, start_minimized=True):
        self.log(
            f"[WARN] Master list verification not implemented for {self.platform_name} yet."
        )
